name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      models:
        description: 'Comma-separated list of models [clip] to push or "all"'
        type: string
        default: 'all'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install ruff
    - name: Lint
      run: |
        ./script/lint



  cog-safe-push:
    runs-on: ubuntu-latest-4-cores
    if: github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Cog
      run: |
        sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
        sudo chmod +x /usr/local/bin/cog

    - name: cog login
      run: |
        echo ${{ secrets.COG_TOKEN }} | cog login --token-stdin

    - name: Install cog-safe-push
      run: |
        pip install git+https://github.com/replicate/cog-safe-push.git

    - name: Push selected models
      env:
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
      run: |
        if [ "${{ inputs.models }}" = "all" ]; then
          models="clip"
        else
          models="${{ inputs.models }}"
        fi

        for model in ${models//,/ }; do
          echo "==="
          echo "==="
          echo "=== Pushing $model"
          echo "==="
          echo "==="

          # CLIP model doesn't need external API keys
          echo "Skipping API key write for $model (CLIP uses local inference)"

          ./script/select-model $model

          cog-safe-push --config cog-safe-push-configs/$model.yaml -vv

          echo "==="
          echo "==="
          echo "=== Pushing underlying official model $model"
          echo "==="
          echo "==="
          ./script/delete-api-key
          cog-safe-push --push-official-model --config cog-safe-push-configs/$model.yaml -vv
        done